<a href="https://colab.research.google.com/github/santhosh-kumar1928/santhoshkumar-codeboosters-2026/blob/main/day2/day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print("All liblaries imported successfully!")
print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.sqlite_version}")

All liblaries imported successfully!
pandas version: 2.2.2
sqlite3 version: 3.37.2

In [5]:
df=pd.read_csv('student_performance.csv')
print(f"Dataset loaded:{df.shape[0]}students,{df.shape[1]}columns")
print((f"columns:{df.columns.tolist()}"))
print("\nFirst 3 rows")
df.head(3)

Dataset loaded:30students,13columns
columns:['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

First 3 rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023

In [8]:
con = sqlite3.connect('college.db')
cursor = con.cursor()
df.to_sql(
    'students',
    con,
    if_exists='replace',
    index=False
    )
cursor.execute("SELECT COUNT(*) FROM students")
count = cursor.fetchone()[0]
print(f"Database 'college.db' created successfully!")
print(f"Table 'students' has {count} rows")

Database 'college.db' created successfully!
Table 'students' has 30 rows

In [ ]:
def run_query(query, description=None):
    if description:
        print(description)
    cursor.execute(query)
    columns = [description[0] for description in cursor.description]
    data = cursor.fetchall()
    return pd.DataFrame(data, columns=columns)

In [20]:
def run_query(query, query_name="SQL Query"):
    try:
        cursor.execute(query)
        results = cursor.fetchall()
        columns = [description[0] for description in cursor.description]
        df_results = pd.DataFrame(results, columns=columns)
        print(f"\n{query_name}:")
        display(df_results)
        return df_results
    except sqlite3.Error as e:
        print(f"Error executing query '{query_name}': {e}")
        return None

In [21]:
query1 = """
    SELECT student_id,name,department,math_score, attendance_percentage
    FROM students
    LIMIT 10
"""
result1 = run_query(query1 , "Query 1: First 10 Students (SELECT + LIMIT)")

Query 1: First 10 Students (SELECT + LIMIT):

,student_id,name,department,math_score,attendance_percentage
0,1001,Aarav Sharma,Computer Science,85,92
1,1002,Priya Patel,Computer Science,76,87
2,1003,Rohit Verma,Electronics,65,78
3,1004,Sneha Reddy,Mechanical,70,95
4,1005,Arjun Nair,Computer Science,92,90
5,1006,Meera Joshi,Electronics,58,72
6,1007,Kiran Kumar,Civil,73,85
7,1008,Divya Singh,Computer Science,88,96
8,1009,Rahul Mishra,Mechanical,62,68
9,1010,Ananya Das,Computer Science,95,98

In [22]:
query1 = """
    SELECT name,department,math_score
    FROM students
    ORDER BY math_score DESC
    LIMIT 5
"""
result1 = run_query(query1 , "Query 2: Top 5 Math Scores (ORDER BY DESC + LIMIT)")

Query 2: Top 5 Math Scores (ORDER BY DESC + LIMIT):

             name        department  math_score
0      Ananya Das  Computer Science          95
1     Tanvi Mehta  Computer Science          93
2      Arjun Nair  Computer Science          92
3  Akanksha Yadav  Computer Science          91
4  Swati Kulkarni  Computer Science          90

In [25]:
query1 = """
    SELECT name,math_score,science_score,programming_score,attendance_percentage
    FROM students
    WHERE department = 'Computer Science'
    ORDER BY programming_score DESC
    LIMIT 14
"""
result1 = run_query(query1 , "Query 3: computer science students (ORDER BY DESC + LIMIT)")

Query 3: computer science students (ORDER BY DESC + LIMIT):

,name,math_score,science_score,programming_score,attendance_percentage
0,Ananya Das,95,89,97,98
1,Tanvi Mehta,93,90,96,97
2,Arjun Nair,92,88,95,90
3,Akanksha Yadav,91,93,94,95
4,Divya Singh,88,91,93,96
5,Swati Kulkarni,90,87,92,94
6,Aarav Sharma,85,78,91,92
7,Amit Bose,86,82,89,91
8,Suresh Rao,83,86,88,88
9,Gaurav Shukla,84,79,87,87
10,Nisha Kapoor,79,84,83,89
11,Priya Patel,76,82,79,87
12,Ajay Tiwari,71,69,76,75

In [31]:
query4 = """
SELECT name,department,attendance_percentage
    FROM students
    WHERE attendance_percentage>90 AND department != 'Civil'
    ORDER BY attendance_percentage DESC
"""
result4= run_query(query4 , "Query 4: attendance_percentage (>90%)exclude civil (ORDER BY DESC)")

Query 4: attendance_percentage (>90%)exclude civil (ORDER BY DESC):

             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3     Sneha Reddy        Mechanical                     95
4  Akanksha Yadav  Computer Science                     95
5  Swati Kulkarni  Computer Science                     94
6    Ritu Agarwal       Electronics                     93
7    Aarav Sharma  Computer Science                     92
8   Kavya Nambiar        Mechanical                     91
9       Amit Bose  Computer Science                     91

In [37]:
query5 = """
SELECT name,department,attendance_percentage
    FROM students
    WHERE attendance_percentage>93 AND department != 'Mechanical'
    ORDER BY attendance_percentage DESC
    LIMIT 5
"""
result5= run_query(query5 , "Query 5: attendance_percentage (>93%)exclude mechanical (ORDER BY DESC)")

Query 5: attendance_percentage (>93%)exclude mechanical (ORDER BY DESC):

             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3  Akanksha Yadav  Computer Science                     95
4  Swati Kulkarni  Computer Science                     94